version: "3.9"

services:
  db:
    image: postgres:16.3-bookworm
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: feedy
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
