// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        int64
	Actor     string
	Action    string
	Target    pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type Feed struct {
	ID        int64
	Name      string
	Url       string
	CreatedAt pgtype.Timestamptz
}

type Subscription struct {
	ID          int64
	BotName     pgtype.Text
	FeedID      int64
	ChannelID   string
	GroupID     string
	PublishedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}
